# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_NPY=110  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=110  CONDA_PY=34
    - CONDA_NPY=111  CONDA_PY=34
    - CONDA_NPY=110  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HY3vSFhvrBCrEZHT2vl1jMctpnGk7h3RaOscifMkwISm2mD3fpccWriYAMJDLmj457XxJD+H3P+pSUp9C4wRd+684KpLbgNDEmHCVYtX/HqvDdkI6e0XmJinqEWwdEPj8BA1hlubEFbIIPxm4lCeTbxIv0d8Sfc2ejhWxuMthftONYN2nRelXYdyv6Q8OqngnLieJy5Vxe+k06bUTtJpTKbjvvIpwsuK2/w7yWAt5THBFJQ2CDjTeCQBPb+WgjtF2KkrHz+53gR1BM3XvTgLjZCw/bMkViJX94i+BvDAgLNRsrJlgUO/o9WyWYJ3Kx3XFwN5ORB2ATPQUcPXMlYwFxQujbcHvaMrpRVb6FBNkC6De61/JOU2SR5WQpLP/LdhHT9zAn6pXRRwC0AOUvk6G3OwiLedhVpOlWAVeYlliC1lJ0YUhlDgBMQs7uaX2qeUXiXIKG5nwxd57Ml6cl078WUO51asDgK8IUTWzIH4cj0v293T58zc1sfCQveQJ7OBlIlREAQ3M4SxwIpHkaa2iLZEWNKZGlE4XttWqYZVWk0SMiDFLo8UYmf9Jyl8u1dTiQhkkAtOrPogt9VpYJ7pikkhDVDQs3sQUnx+0G5kX2hC9EMlMT2pOwGitkNxdBga2zweQUwY8Nu+qcJMk1oNypE8lg0E3fdio7VY7Ws4+40="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
