travis:
  secure:
    BINSTAR_TOKEN: HY3vSFhvrBCrEZHT2vl1jMctpnGk7h3RaOscifMkwISm2mD3fpccWriYAMJDLmj457XxJD+H3P+pSUp9C4wRd+684KpLbgNDEmHCVYtX/HqvDdkI6e0XmJinqEWwdEPj8BA1hlubEFbIIPxm4lCeTbxIv0d8Sfc2ejhWxuMthftONYN2nRelXYdyv6Q8OqngnLieJy5Vxe+k06bUTtJpTKbjvvIpwsuK2/w7yWAt5THBFJQ2CDjTeCQBPb+WgjtF2KkrHz+53gR1BM3XvTgLjZCw/bMkViJX94i+BvDAgLNRsrJlgUO/o9WyWYJ3Kx3XFwN5ORB2ATPQUcPXMlYwFxQujbcHvaMrpRVb6FBNkC6De61/JOU2SR5WQpLP/LdhHT9zAn6pXRRwC0AOUvk6G3OwiLedhVpOlWAVeYlliC1lJ0YUhlDgBMQs7uaX2qeUXiXIKG5nwxd57Ml6cl078WUO51asDgK8IUTWzIH4cj0v293T58zc1sfCQveQJ7OBlIlREAQ3M4SxwIpHkaa2iLZEWNKZGlE4XttWqYZVWk0SMiDFLo8UYmf9Jyl8u1dTiQhkkAtOrPogt9VpYJ7pikkhDVDQs3sQUnx+0G5kX2hC9EMlMT2pOwGitkNxdBga2zweQUwY8Nu+qcJMk1oNypE8lg0E3fdio7VY7Ws4+40=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
